### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Yancccccc** [JungbinLim/GGAE-public#2]
C:\Users\Yanc\.conda\envs\pytorch\python.exe D:/IOE/B2S1/GGAE-public-main/train.py 
Traceback (most recent call last):
  File "D:/IOE/B2S1/GGAE-public-main/train.py", line 132, in <module>
    cfg = OmegaConf.load(args.config)
  File "C:\Users\Yanc\.conda\envs\pytorch\lib\site-packages\omegaconf\omegaconf.py", line 194, in load
    raise TypeError("Unexpected file type")
TypeError: Unexpected file type
{}
我怀疑是    parser = argparse.ArgumentParser()
    parser.add_argument("--config", type=str)
    parser.add_argument("--device", default=None)
    parser.add_argument("--logdir", default=None)
    parser.add_argument("--run", default=None)
    parser.add_argument("--seed", default=0, type=int)这里参数的问题，您可以提供一下原始代码的参数吗

**Comment by JungbinLim** [comment]
Thank you for your comment!
We've added dataset generation codes (`.ipynb` files) and command-line instructions to run the experiments. Please check out the updated `README.md`!
